// Generated by dts-bundle v0.3.0

declare module 'cu-stores' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import CharacterStore from '__cu-stores/classes/CharacterStore';
    import EnemyTargetStore from '__cu-stores/classes/EnemyTargetStore';
    import FriendlyTargetStore from '__cu-stores/classes/FriendlyTargetStore';
    export { CharacterStore, EnemyTargetStore, FriendlyTargetStore };
}

declare module '__cu-stores/classes/CharacterStore' {
    const CharacterStore: {
        create(): any;
    };
    export default CharacterStore;
}

declare module '__cu-stores/classes/EnemyTargetStore' {
    const EnemyTargetStore: {
        create(): any;
    };
    export default EnemyTargetStore;
}

declare module '__cu-stores/classes/FriendlyTargetStore' {
    const FriendlyTargetStore: {
        create(): any;
    };
    export default FriendlyTargetStore;
}

