// Generated by dts-bundle v0.3.0

declare module 'cu-stores' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import AnnouncementsStore from '__cu-stores/classes/AnnouncementsStore';
    import CharacterStore from '__cu-stores/classes/CharacterStore';
    import EnemyTargetStore from '__cu-stores/classes/EnemyTargetStore';
    import FriendlyTargetStore from '__cu-stores/classes/FriendlyTargetStore';
    import ControlGameStore from '__cu-stores/classes/ControlGameStore';
    import ControlGameScoreStore from '__cu-stores/classes/ControlGameScoreStore';
    export { AnnouncementsStore, CharacterStore, EnemyTargetStore, FriendlyTargetStore, ControlGameStore, ControlGameScoreStore };
}

declare module '__cu-stores/classes/AnnouncementsStore' {
    const AnnouncementsStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default AnnouncementsStore;
}

declare module '__cu-stores/classes/CharacterStore' {
    const CharacterStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default CharacterStore;
}

declare module '__cu-stores/classes/EnemyTargetStore' {
    const EnemyTargetStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default EnemyTargetStore;
}

declare module '__cu-stores/classes/FriendlyTargetStore' {
    const FriendlyTargetStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default FriendlyTargetStore;
}

declare module '__cu-stores/classes/ControlGameStore' {
    const ControlGameStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default ControlGameStore;
}

declare module '__cu-stores/classes/ControlGameScoreStore' {
    const ControlGameScoreStore: {
        create(): {
            store: any;
            actions: any;
        };
    };
    export default ControlGameScoreStore;
}

